spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart.max-file-size: 100MB
    multipart:
      max-request-size: 128MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./gameVerse2_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
