spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 128MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./gameVerse2_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ec511be6db16cca7e3d10f4dc80bcc8d
            client-secret: ""  # 카카오는 클라이언트 시크릿을 사용하지 않음
            redirect-uri: "http://localhost:8080/auth/kakao/callback"
            authorization-grant-type: authorization_code
            scope: profile, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
